### ISSUE TITLE
Modifiers on subsystems in robot container

### ISSUE THREAD

**Issue by iwei20** [StuyPulse/Edwin#15]
https://github.com/StuyPulse/fantastic-spork/blob/af158b0283fb068a53b7eac73f1098c37ee75356/src/main/java/com/stuypulse/robot/RobotContainer.java#L25-L28

Should all these be public?

**Comment by Sam-Belliveau** [comment]
Eh, like other groups just made them public but they aren't supposed to be

**Comment by iwei20** [comment]
Why?
